# Generated by Django 3.2.25 on 2024-12-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(default='')),
                ('abs_name', models.CharField(default='', max_length=254)),
                ('abs_video', models.FileField(blank=True, null=True, upload_to='')),
                ('abs_description', models.TextField(default='')),
                ('sets', models.IntegerField(default=1)),
                ('reps', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('description', models.TextField()),
                ('calories_per_day', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
