# Generated by Django 3.2.25 on 2024-12-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
