# Generated by Django 3.2.25 on 2024-12-31 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_mealplan_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='calories_per_day',
            new_name='calories',
        ),
    ]
