# Generated by Django 4.2 on 2025-01-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_exercise_abs_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('sets', models.IntegerField(blank=True, default=1, null=True)),
                ('reps', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlutesExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('sets', models.IntegerField(blank=True, default=1, null=True)),
                ('reps', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
