# Generated by Django 4.2 on 2025-01-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_absexercise_glutesexercise_delete_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absexercise',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='absexercise',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='absexercise',
            name='reps',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='absexercise',
            name='sets',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='glutesexercise',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='glutesexercise',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='glutesexercise',
            name='reps',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='glutesexercise',
            name='sets',
            field=models.IntegerField(default=1),
        ),
    ]
