# Generated by Django 3.2.25 on 2024-12-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
