# Generated by Django 4.2 on 2025-01-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='reply',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
