# Generated by Django 3.2.25 on 2024-12-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20241212_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abs_exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('sets1', models.IntegerField(blank=True, null=True)),
                ('reps1', models.IntegerField(blank=True, null=True)),
                ('sets2', models.IntegerField(blank=True, null=True)),
                ('reps2', models.IntegerField(blank=True, null=True)),
                ('sets3', models.IntegerField(blank=True, null=True)),
                ('reps3', models.IntegerField(blank=True, null=True)),
                ('sets4', models.IntegerField(blank=True, null=True)),
                ('reps4', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
