# Generated by Django 3.2.25 on 2024-12-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_abs_exercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abs_exercise',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
