# Generated by Django 3.2.25 on 2024-12-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20241214_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
