# Generated by Django 3.2.25 on 2024-12-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='slug',
        ),
    ]
