# Generated by Django 3.2.25 on 2024-12-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_remove_exercise_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='reps1',
            new_name='reps',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='reps2',
            new_name='sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps3',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps4',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets1',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets2',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets3',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets4',
        ),
        migrations.AddField(
            model_name='exercise',
            name='abs_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='abs_name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='exercise',
            name='abs_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
