# Generated by Django 3.2.25 on 2024-12-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_auto_20241230_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='abs_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(default=1),
        ),
    ]
