# Generated by Django 3.2.25 on 2024-12-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
