# Generated by Django 4.2 on 2025-01-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_mealplan_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
